{% set name = "tox-uv" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tox_uv-{{ version }}.tar.gz
  sha256: c1f04b59a649912eb9a91a1f4f303a5c86747c978a73bdf5f99a1c956dfc5872

build:
  noarch: python
  script:
    - sed -i '/"uv/d' ./pyproject.toml && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [linux]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [win or osx]
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
  run:
    - python >={{ python_min }}
    - packaging >=24.1
    - tox <5,>=4.21.2
    - typing_extensions >=4.12.2
    - uv <1,>=0.4.18

test:
  imports:
    - tox_uv
  commands:
  # pip check fails because uv is part of base env, remove uv from pyproject.toml and enable pip check for linux only
    - pip check  # [linux]
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Integration of uv with tox.
  dev_url: https://github.com/tox-dev/tox-uv
  home: https://github.com/tox-dev/tox-uv
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
